### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by John1326** [Everhusk/RGP-Gen#4]
Hello,

I never used fortran so far. But i really Need this tool to create RGP Files.
Just as you said I opened the F90 File in simplyfortran, saved as project and pressed the button "Build Now".
But then there are a couple of Errors like "undefined reference to".
It seems like fortran can't find the Refprop Subroutines in the "fortran" Folder of Refprop.

So how can i tell fortran where These Subroutines are? How can i refer them to fortran?

Thanks for help and this nice tool so far!

**Comment by sangheraio** [comment]
Hey try the new version out, should be a bit easier to deal with.
